//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace шанс
{
    using System;
    using System.Collections.Generic;
    
    public partial class dolj
    {
        public int doljID { get; set; }
        public string obiazanosti { get; set; }
        public Nullable<int> ZP { get; set; }
    }
}
